apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy01
  name: deploy01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy01
  template:
    metadata:
      labels:
        app: deploy01
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: deploy01
      containers:
        - command:
          - sh
          - -c
          - sleep 3600
          image: busybox:1.36.1
          name: busybox
