apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bb-deploy
  name: bb-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bb-deploy
  template:
    metadata:
      labels:
        app: bb-deploy
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      containers:
        - command:
          - sh
          - -c
          - sleep 3600
          image: busybox:1.36.1
          name: busybox
